version: 0.2

phases:
  pre_build:
    commands:
      - echo "Hello from my pipeline"
  build:
    commands:
      - pip install pipenv
      - pipenv install
      - python -m unittest 
  post_build:
    commands:
      - echo Build completed on `date`
